---
"$schema": https://json-schema.org/draft/2020-12/schema
title: Overture Maps Schema
description: >-
  A JSON Schema for the canonical GeoJSON form of Overture Maps
  Features.
type: object
unevaluatedProperties: false
allOf:
  - "$ref": https://geojson.org/schema/Feature.json
    "$comment": Every Overture feature IS A GeoJSON feature
oneOf:
  - if:
      properties:
        properties:
          properties:
            theme: { enum: [addresses] }
            type: { enum: [address] }
    then: { "$ref": "bblocks://ogc.overturemaps.schemas.addresses.address" }
    else: { propertyNames: false }
  - if:
      properties:
        properties:
          properties:
            theme: { enum: [base] }
            type: { enum: [bathymetry] }
    then: { "$ref": "bblocks://ogc.overturemaps.schemas.base.bathymetry" }
    else: { propertyNames: false }
  - if:
      properties:
        properties:
          properties:
            theme: { enum: [base] }
            type: { enum: [infrastructure] }
    then: { "$ref": "bblocks://ogc.overturemaps.schemas.base.infrastructure" }
    else: { propertyNames: false }
  - if:
      properties:
        properties:
          properties:
            theme: { enum: [base] }
            type: { enum: [land] }
    then: { "$ref": "bblocks://ogc.overturemaps.schemas.base.land" }
    else: { propertyNames: false }
  - if:
      properties:
        properties:
          properties:
            theme: { enum: [base] }
            type: { enum: [land_cover] }
    then: { "$ref": "bblocks://ogc.overturemaps.schemas.base.land_cover" }
    else: { propertyNames: false }
  - if:
      properties:
        properties:
          properties:
            theme: { enum: [base] }
            type: { enum: [land_use] }
    then: { "$ref": "bblocks://ogc.overturemaps.schemas.base.land_use" }
    else: { propertyNames: false }
  - if:
      properties:
        properties:
          properties:
            theme: { enum: [base] }
            type: { enum: [water] }
    then: { "$ref": "bblocks://ogc.overturemaps.schemas.base.water" }
    else: { propertyNames: false }
  - if:
      properties:
        properties:
          properties:
            theme: { enum: [buildings] }
            type: { enum: [building] }
    then: { "$ref": "bblocks://ogc.overturemaps.schemas.buildings.building" }
    else: { propertyNames: false }
  - if:
      properties:
        properties:
          properties:
            theme: { enum: [buildings] }
            type: { enum: [building_part] }
    then: { "$ref": "bblocks://ogc.overturemaps.schemas.buildings.building_part" }
    else: { propertyNames: false }
  - if:
      properties:
        properties:
          properties:
            theme: { enum: [divisions] }
            type: { enum: [division_boundary] }
    then: { "$ref": "bblocks://ogc.overturemaps.schemas.divisions.division_boundary" }
    else: { propertyNames: false }
  - if:
      properties:
        properties:
          properties:
            theme: { enum: [divisions] }
            type: { enum: [division] }
    then: { "$ref": "bblocks://ogc.overturemaps.schemas.divisions.division" }
    else: { propertyNames: false }
  - if:
      properties:
        properties:
          properties:
            theme: { enum: [divisions] }
            type: { enum: [division_area] }
    then: { "$ref": "bblocks://ogc.overturemaps.schemas.divisions.division_area" }
    else: { propertyNames: false }
  - if:
      properties:
        properties:
          properties:
            theme: { enum: [places] }
            type: { enum: [place] }
    then: { "$ref": "bblocks://ogc.overturemaps.schemas.places.place" }
    else: { propertyNames: false }
  - if:
      properties:
        properties:
          properties:
            theme: { enum: [transportation] }
            type: { enum: [connector] }
    then: { "$ref": "bblocks://ogc.overturemaps.schemas.transportation.connector" }
    else: { propertyNames: false }
  - if:
      properties:
        properties:
          properties:
            theme: { enum: [transportation] }
            type: { enum: [segment] }
    then: { "$ref": "bblocks://ogc.overturemaps.schemas.transportation.segment" }
    else: { propertyNames: false }
