"$schema": https://json-schema.org/draft/2020-12/schema
title: Overture Maps Schema
description: >-
  A JSON Schema for the canonical GeoJSON form of Overture Maps
  Features.
type: object
unevaluatedProperties: false
allOf:
  - "$ref": https://geojson.org/schema/Feature.json
    "$comment": Every Overture feature IS A GeoJSON feature
oneOf:
  - "$ref": "bblocks://ogc.overturemaps.schemas.addresses.address"
  - "$ref": "bblocks://ogc.overturemaps.schemas.base.bathymetry"
  - "$ref": "bblocks://ogc.overturemaps.schemas.base.infrastructure"
  - "$ref": "bblocks://ogc.overturemaps.schemas.base.land"
  - "$ref": "bblocks://ogc.overturemaps.schemas.base.land_cover"
  - "$ref": "bblocks://ogc.overturemaps.schemas.base.land_use"
  - "$ref": "bblocks://ogc.overturemaps.schemas.base.water"
  - "$ref": "bblocks://ogc.overturemaps.schemas.buildings.building"
  - "$ref": "bblocks://ogc.overturemaps.schemas.buildings.building_part"
  - "$ref": "bblocks://ogc.overturemaps.schemas.divisions.division_boundary"
  - "$ref": "bblocks://ogc.overturemaps.schemas.divisions.division"
  - "$ref": "bblocks://ogc.overturemaps.schemas.divisions.division_area"
  - "$ref": "bblocks://ogc.overturemaps.schemas.places.place"
  - "$ref": "bblocks://ogc.overturemaps.schemas.transportation.connector"
  - "$ref": "bblocks://ogc.overturemaps.schemas.transportation.segment"
