"$schema": https://json-schema.org/draft/2020-12/schema
title: connector
description: >-
  Connectors create physical connections between segments. Connectors
  are compatible with GeoJSON Point features.
type: object
properties:
  id:
    "$ref": bblocks://ogc.overturemaps.schemas.definitions#/$defs/propertyDefinitions/id
  geometry:
    description: >-
      Connector's geometry which MUST be a Point as defined by GeoJSON
      schema.
    unevaluatedProperties: false
    allOf:
      - "$ref": https://geojson.org/schema/Point.json
  properties:
    unevaluatedProperties: false
    allOf:
      - "$ref": bblocks://ogc.overturemaps.schemas.definitions#/$defs/propertyContainers/overtureFeaturePropertiesContainer
    required: [ theme, type ]
    properties:
      theme:
        const: transportation
      type:
        const: connector